input:
  label: "mqtt"
  mqtt:
    urls:
      - "tcp://${MQTT_SERVER}:1883"
    client_id: ""
    connect_timeout: "30s"
    topics:
      - "msh/#"
      - "meshtastic/#"
      - "rdz_sonde_server/#"
    auto_replay_nacks: true
pipeline:
  processors:
    - label: "bloblang"
      bloblang: from "${CONF_DIR}meshtastic.blobl"
output:
  label: "stdout"
  stdout:
    codec: "lines"
